version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: wb-redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: wb-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure