server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:wb;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  data:
    redis:
      host: localhost
      port: 6379